/*
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/ChronoSheetsClient/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/ChronoSheetsClient/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ChronoSheetsApi);
  }
}(this, function(expect, ChronoSheetsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ChronoSheetsApi.AggregateJobTasksApi();
  });

  describe('ChronoSheetsClient', function() {
    describe('AggregateJobTasksApi', function() {
      describe('aggregateJobTasksGetAggregateJobTasks', function() {
        it('should call aggregateJobTasksGetAggregateJobTasks successfully', function(done) {
          // TODO: uncomment, update parameter values for aggregateJobTasksGetAggregateJobTasks call and complete the assertions
          /*
          var xChronosheetsAuth = "xChronosheetsAuth_example";

          instance.aggregateJobTasksGetAggregateJobTasks(xChronosheetsAuth, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ChronoSheetsApi.CSApiResponseListAggregateJobCode);
            {
              let dataCtr = data.data;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(ChronoSheetsApi.CSAggregateJobCode);
                {
                  let dataCtr = data.availableTasks;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a(ChronoSheetsApi.CSAggregateJobTask);
                    expect(data.id).to.be.a('number');
                    expect(data.id).to.be(0);
                    expect(data.label).to.be.a('string');
                    expect(data.label).to.be("");
                    expect(data.isDeleted).to.be.a('boolean');
                    expect(data.isDeleted).to.be(false);
    
                          }
                }
                {
                  let dataCtr = data.permittedEmployees;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a('number');
                    expect(data).to.be(0);
                  }
                }
                expect(data.id).to.be.a('number');
                expect(data.id).to.be(0);
                expect(data.code).to.be.a('string');
                expect(data.code).to.be("");
                expect(data.client).to.be.a('string');
                expect(data.client).to.be("");
                expect(data.clientId).to.be.a('number');
                expect(data.clientId).to.be(0);
                expect(data.project).to.be.a('string');
                expect(data.project).to.be("");
                expect(data.projectId).to.be.a('number');
                expect(data.projectId).to.be(0);
                expect(data.organisationId).to.be.a('number');
                expect(data.organisationId).to.be(0);
                expect(data.isDeleted).to.be.a('boolean');
                expect(data.isDeleted).to.be(false);

                      }
            }
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("Succeeded");
            expect(data.message).to.be.a('string');
            expect(data.message).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
