/*
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/ChronoSheetsClient/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/ChronoSheetsClient/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ChronoSheetsApi);
  }
}(this, function(expect, ChronoSheetsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ChronoSheetsApi.OrganisationApi();
  });

  describe('ChronoSheetsClient', function() {
    describe('OrganisationApi', function() {
      describe('organisationGetOrganisation', function() {
        it('should call organisationGetOrganisation successfully', function(done) {
          // TODO: uncomment, update parameter values for organisationGetOrganisation call and complete the assertions
          /*
          var xChronosheetsAuth = "xChronosheetsAuth_example";

          instance.organisationGetOrganisation(xChronosheetsAuth, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ChronoSheetsApi.CSApiResponseOrganisation);
            expect(data.data).to.be.a(ChronoSheetsApi.CSOrganisation);
                  expect(data.data.id).to.be.a('number');
              expect(data.data.id).to.be(0);
              expect(data.data.name).to.be.a('string');
              expect(data.data.name).to.be("");
              expect(data.data.addressLine01).to.be.a('string');
              expect(data.data.addressLine01).to.be("");
              expect(data.data.addressLine02).to.be.a('string');
              expect(data.data.addressLine02).to.be("");
              expect(data.data.suburb).to.be.a('string');
              expect(data.data.suburb).to.be("");
              expect(data.data.state).to.be.a('string');
              expect(data.data.state).to.be("");
              expect(data.data.postcode).to.be.a('string');
              expect(data.data.postcode).to.be("");
              expect(data.data.country).to.be.a('string');
              expect(data.data.country).to.be("");
              expect(data.data.phone).to.be.a('string');
              expect(data.data.phone).to.be("");
              expect(data.data.emailAddress).to.be.a('string');
              expect(data.data.emailAddress).to.be("");
              expect(data.data.timezone).to.be.a('string');
              expect(data.data.timezone).to.be("");
              expect(data.data.subscriptionCustomerId).to.be.a('string');
              expect(data.data.subscriptionCustomerId).to.be("");
              expect(data.data.signupToken).to.be.a('string');
              expect(data.data.signupToken).to.be("");
              expect(data.data.isActive).to.be.a('boolean');
              expect(data.data.isActive).to.be(false);
              expect(data.data.stripeCouponCode).to.be.a('string');
              expect(data.data.stripeCouponCode).to.be("");
              expect(data.data.subscriptionSource).to.be.a('string');
              expect(data.data.subscriptionSource).to.be("None");
              expect(data.data.signUpSource).to.be.a('string');
              expect(data.data.signUpSource).to.be("Desktop");
              expect(data.data.mobileSignUpCode).to.be.a('string');
              expect(data.data.mobileSignUpCode).to.be("");
              expect(data.data.subscriptionCycleStart).to.be.a(Date);
              expect(data.data.subscriptionCycleStart).to.be(new Date());
              expect(data.data.subscriptionCycleEnd).to.be.a(Date);
              expect(data.data.subscriptionCycleEnd).to.be(new Date());
              {
                let dataCtr = data.data.pricingPlans;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a(ChronoSheetsApi.CSOrganisationPricingPlan);
                  expect(data.planId).to.be.a('string');
                  expect(data.planId).to.be("");
                  expect(data.quantity).to.be.a('number');
                  expect(data.quantity).to.be(0);
  
                        }
              }
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("Succeeded");
            expect(data.message).to.be.a('string');
            expect(data.message).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('organisationUpdateOrganisation', function() {
        it('should call organisationUpdateOrganisation successfully', function(done) {
          // TODO: uncomment, update parameter values for organisationUpdateOrganisation call and complete the assertions
          /*
          var request = new ChronoSheetsApi.CSUpdateOrganisationRequest();
          request.organsationId = 0;
          request.organisationName = "";
          request.addressLine01 = "";
          request.addressLine02 = "";
          request.organisationSuburb = "";
          request.organisationState = "";
          request.organisationPostcode = "";
          request.organisationCountry = "";
          request.organisationPhone = "";
          request.organisationEmailAddress = "";
          var xChronosheetsAuth = "xChronosheetsAuth_example";

          instance.organisationUpdateOrganisation(request, xChronosheetsAuth, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ChronoSheetsApi.CSApiResponseUpdateOrganisationResponse);
            expect(data.data).to.be.a(ChronoSheetsApi.CSUpdateOrganisationResponse);
                  {
                let dataCtr = data.data.validationErrors;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a('string');
                  expect(data).to.be("");
                }
              }
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("Succeeded");
            expect(data.message).to.be.a('string');
            expect(data.message).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
