/*
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/ChronoSheetsClient/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/ChronoSheetsClient/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ChronoSheetsApi);
  }
}(this, function(expect, ChronoSheetsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ChronoSheetsApi.TripsApi();
  });

  describe('ChronoSheetsClient', function() {
    describe('TripsApi', function() {
      describe('tripsCreateTrip', function() {
        it('should call tripsCreateTrip successfully', function(done) {
          // TODO: uncomment, update parameter values for tripsCreateTrip call and complete the assertions
          /*
          var request = new ChronoSheetsApi.CSCreateTripRequest();
          request.timesheetId = 0;
          request.vehicleId = 0;
          request.pathCoordsStringCsv = "";
          request.distanceMeters = 0.0;
          request.mobilePlatform = "Unknown";
          var xChronosheetsAuth = "xChronosheetsAuth_example";

          instance.tripsCreateTrip(request, xChronosheetsAuth, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ChronoSheetsApi.CSApiResponseInt32);
            expect(data.data).to.be.a('number');
            expect(data.data).to.be(0);
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("Succeeded");
            expect(data.message).to.be.a('string');
            expect(data.message).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tripsGetMyTripById', function() {
        it('should call tripsGetMyTripById successfully', function(done) {
          // TODO: uncomment, update parameter values for tripsGetMyTripById call and complete the assertions
          /*
          var tripId = 56;
          var xChronosheetsAuth = "xChronosheetsAuth_example";

          instance.tripsGetMyTripById(tripId, xChronosheetsAuth, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ChronoSheetsApi.CSApiResponseTrip);
            expect(data.data).to.be.a(ChronoSheetsApi.CSTrip);
                  expect(data.data.tripId).to.be.a('number');
              expect(data.data.tripId).to.be(0);
              expect(data.data.timesheetId).to.be.a('number');
              expect(data.data.timesheetId).to.be(0);
              expect(data.data.vehicleId).to.be.a('number');
              expect(data.data.vehicleId).to.be(0);
              expect(data.data.userId).to.be.a('number');
              expect(data.data.userId).to.be(0);
              expect(data.data.orgId).to.be.a('number');
              expect(data.data.orgId).to.be(0);
              expect(data.data.mobilePlatform).to.be.a('string');
              expect(data.data.mobilePlatform).to.be("Unknown");
              expect(data.data.startDate).to.be.a(Date);
              expect(data.data.startDate).to.be(new Date());
              expect(data.data.endDate).to.be.a(Date);
              expect(data.data.endDate).to.be(new Date());
              expect(data.data.vehicleName).to.be.a('string');
              expect(data.data.vehicleName).to.be("");
              expect(data.data.vehicleMake).to.be.a('string');
              expect(data.data.vehicleMake).to.be("");
              expect(data.data.vehicleModel).to.be.a('string');
              expect(data.data.vehicleModel).to.be("");
              expect(data.data.vehicleYear).to.be.a('string');
              expect(data.data.vehicleYear).to.be("");
              expect(data.data.costPerKilometer).to.be.a('number');
              expect(data.data.costPerKilometer).to.be(0.0);
              expect(data.data.tripTotalCost).to.be.a('number');
              expect(data.data.tripTotalCost).to.be(0.0);
              expect(data.data.totalTripDistanceMeters).to.be.a('number');
              expect(data.data.totalTripDistanceMeters).to.be(0.0);
              expect(data.data.startAddress).to.be.a('string');
              expect(data.data.startAddress).to.be("");
              expect(data.data.endAddress).to.be.a('string');
              expect(data.data.endAddress).to.be("");
              {
                let dataCtr = data.data.pathCoordinates;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a(ChronoSheetsApi.CSTripCoordinate);
                  expect(data.latitude).to.be.a('number');
                  expect(data.latitude).to.be(0.0);
                  expect(data.longitude).to.be.a('number');
                  expect(data.longitude).to.be(0.0);
  
                        }
              }
              expect(data.data.cacheExpiryDate).to.be.a(Date);
              expect(data.data.cacheExpiryDate).to.be(new Date());
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("Succeeded");
            expect(data.message).to.be.a('string');
            expect(data.message).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('tripsGetMyTrips', function() {
        it('should call tripsGetMyTrips successfully', function(done) {
          // TODO: uncomment, update parameter values for tripsGetMyTrips call and complete the assertions
          /*
          var startDate = new Date("2013-10-20T19:20:30+01:00");
          var endDate = new Date("2013-10-20T19:20:30+01:00");
          var xChronosheetsAuth = "xChronosheetsAuth_example";
          var opts = {};
          opts.skip = 56;
          opts.take = 56;
          opts.vehicleId = 56;

          instance.tripsGetMyTrips(startDate, endDate, xChronosheetsAuth, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ChronoSheetsApi.CSApiResponseForPaginatedListTrip);
            expect(data.totalSetCount).to.be.a('number');
            expect(data.totalSetCount).to.be(0);
            {
              let dataCtr = data.data;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(ChronoSheetsApi.CSTrip);
                expect(data.tripId).to.be.a('number');
                expect(data.tripId).to.be(0);
                expect(data.timesheetId).to.be.a('number');
                expect(data.timesheetId).to.be(0);
                expect(data.vehicleId).to.be.a('number');
                expect(data.vehicleId).to.be(0);
                expect(data.userId).to.be.a('number');
                expect(data.userId).to.be(0);
                expect(data.orgId).to.be.a('number');
                expect(data.orgId).to.be(0);
                expect(data.mobilePlatform).to.be.a('string');
                expect(data.mobilePlatform).to.be("Unknown");
                expect(data.startDate).to.be.a(Date);
                expect(data.startDate).to.be(new Date());
                expect(data.endDate).to.be.a(Date);
                expect(data.endDate).to.be(new Date());
                expect(data.vehicleName).to.be.a('string');
                expect(data.vehicleName).to.be("");
                expect(data.vehicleMake).to.be.a('string');
                expect(data.vehicleMake).to.be("");
                expect(data.vehicleModel).to.be.a('string');
                expect(data.vehicleModel).to.be("");
                expect(data.vehicleYear).to.be.a('string');
                expect(data.vehicleYear).to.be("");
                expect(data.costPerKilometer).to.be.a('number');
                expect(data.costPerKilometer).to.be(0.0);
                expect(data.tripTotalCost).to.be.a('number');
                expect(data.tripTotalCost).to.be(0.0);
                expect(data.totalTripDistanceMeters).to.be.a('number');
                expect(data.totalTripDistanceMeters).to.be(0.0);
                expect(data.startAddress).to.be.a('string');
                expect(data.startAddress).to.be("");
                expect(data.endAddress).to.be.a('string');
                expect(data.endAddress).to.be("");
                {
                  let dataCtr = data.pathCoordinates;
                  expect(dataCtr).to.be.an(Array);
                  expect(dataCtr).to.not.be.empty();
                  for (let p in dataCtr) {
                    let data = dataCtr[p];
                    expect(data).to.be.a(ChronoSheetsApi.CSTripCoordinate);
                    expect(data.latitude).to.be.a('number');
                    expect(data.latitude).to.be(0.0);
                    expect(data.longitude).to.be.a('number');
                    expect(data.longitude).to.be(0.0);
    
                          }
                }
                expect(data.cacheExpiryDate).to.be.a(Date);
                expect(data.cacheExpiryDate).to.be(new Date());

                      }
            }
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("Succeeded");
            expect(data.message).to.be.a('string');
            expect(data.message).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
