/*
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src/ChronoSheetsClient/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src/ChronoSheetsClient/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ChronoSheetsApi);
  }
}(this, function(expect, ChronoSheetsApi) {
  'use strict';

  var instance;

  describe('ChronoSheetsClient', function() {
    describe('CSProjectCostingReportItem', function() {
      beforeEach(function() {
        instance = new ChronoSheetsApi.CSProjectCostingReportItem();
      });

      it('should create an instance of CSProjectCostingReportItem', function() {
        // TODO: update the code to test CSProjectCostingReportItem
        expect(instance).to.be.a(ChronoSheetsApi.CSProjectCostingReportItem);
      });

      it('should have the property projectId (base name: "ProjectId")', function() {
        // TODO: update the code to test the property projectId
        expect(instance).to.have.property('projectId');
        // expect(instance.projectId).to.be(expectedValueLiteral);
      });

      it('should have the property projectName (base name: "ProjectName")', function() {
        // TODO: update the code to test the property projectName
        expect(instance).to.have.property('projectName');
        // expect(instance.projectName).to.be(expectedValueLiteral);
      });

      it('should have the property clientId (base name: "ClientId")', function() {
        // TODO: update the code to test the property clientId
        expect(instance).to.have.property('clientId');
        // expect(instance.clientId).to.be(expectedValueLiteral);
      });

      it('should have the property organisationId (base name: "OrganisationId")', function() {
        // TODO: update the code to test the property organisationId
        expect(instance).to.have.property('organisationId');
        // expect(instance.organisationId).to.be(expectedValueLiteral);
      });

      it('should have the property clientName (base name: "ClientName")', function() {
        // TODO: update the code to test the property clientName
        expect(instance).to.have.property('clientName');
        // expect(instance.clientName).to.be(expectedValueLiteral);
      });

      it('should have the property estimatedCost (base name: "EstimatedCost")', function() {
        // TODO: update the code to test the property estimatedCost
        expect(instance).to.have.property('estimatedCost');
        // expect(instance.estimatedCost).to.be(expectedValueLiteral);
      });

      it('should have the property actualCostFiltered (base name: "ActualCostFiltered")', function() {
        // TODO: update the code to test the property actualCostFiltered
        expect(instance).to.have.property('actualCostFiltered');
        // expect(instance.actualCostFiltered).to.be(expectedValueLiteral);
      });

      it('should have the property actualCost (base name: "ActualCost")', function() {
        // TODO: update the code to test the property actualCost
        expect(instance).to.have.property('actualCost');
        // expect(instance.actualCost).to.be(expectedValueLiteral);
      });

    });
  });

}));
