/**
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/ChronoSheetsClient/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/ChronoSheetsClient/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ChronoSheetsApi);
  }
}(this, function(expect, ChronoSheetsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ChronoSheetsApi.OrganisationGroupsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrganisationGroupsApi', function() {
    describe('organisationGroupsCreateOrganisationGroup', function() {
      it('should call organisationGroupsCreateOrganisationGroup successfully', function(done) {
        //uncomment below and update the code to test organisationGroupsCreateOrganisationGroup
        //instance.organisationGroupsCreateOrganisationGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('organisationGroupsDeleteOrganisationGroup', function() {
      it('should call organisationGroupsDeleteOrganisationGroup successfully', function(done) {
        //uncomment below and update the code to test organisationGroupsDeleteOrganisationGroup
        //instance.organisationGroupsDeleteOrganisationGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('organisationGroupsGetOrganisationGroup', function() {
      it('should call organisationGroupsGetOrganisationGroup successfully', function(done) {
        //uncomment below and update the code to test organisationGroupsGetOrganisationGroup
        //instance.organisationGroupsGetOrganisationGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('organisationGroupsGetOrganisationGroups', function() {
      it('should call organisationGroupsGetOrganisationGroups successfully', function(done) {
        //uncomment below and update the code to test organisationGroupsGetOrganisationGroups
        //instance.organisationGroupsGetOrganisationGroups(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('organisationGroupsGetOrganisationGroupsForJob', function() {
      it('should call organisationGroupsGetOrganisationGroupsForJob successfully', function(done) {
        //uncomment below and update the code to test organisationGroupsGetOrganisationGroupsForJob
        //instance.organisationGroupsGetOrganisationGroupsForJob(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('organisationGroupsGetOrganisationGroupsForVehicle', function() {
      it('should call organisationGroupsGetOrganisationGroupsForVehicle successfully', function(done) {
        //uncomment below and update the code to test organisationGroupsGetOrganisationGroupsForVehicle
        //instance.organisationGroupsGetOrganisationGroupsForVehicle(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('organisationGroupsUpdateOrganisationGroup', function() {
      it('should call organisationGroupsUpdateOrganisationGroup successfully', function(done) {
        //uncomment below and update the code to test organisationGroupsUpdateOrganisationGroup
        //instance.organisationGroupsUpdateOrganisationGroup(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
