/**
 * ChronoSheets API
 * ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.
 *
 * OpenAPI spec version: v1
 * Contact: lachlan@chronosheets.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ChronoSheetsClient/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ChronoSheetsApi) {
      root.ChronoSheetsApi = {};
    }
    root.ChronoSheetsApi.CsApiUserHourlyRate = factory(root.ChronoSheetsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CsApiUserHourlyRate model module.
   * @module ChronoSheetsClient/ChronoSheetsClientLibModel/CsApiUserHourlyRate
   * @version v1
   */

  /**
   * Constructs a new <code>CsApiUserHourlyRate</code>.
   * @alias module:ChronoSheetsClient/ChronoSheetsClientLibModel/CsApiUserHourlyRate
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>CsApiUserHourlyRate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:ChronoSheetsClient/ChronoSheetsClientLibModel/CsApiUserHourlyRate} obj Optional instance to populate.
   * @return {module:ChronoSheetsClient/ChronoSheetsClientLibModel/CsApiUserHourlyRate} The populated <code>CsApiUserHourlyRate</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('RateId')) {
        obj['RateId'] = ApiClient.convertToType(data['RateId'], 'Number');
      }
      if (data.hasOwnProperty('UserId')) {
        obj['UserId'] = ApiClient.convertToType(data['UserId'], 'Number');
      }
      if (data.hasOwnProperty('OrganisationId')) {
        obj['OrganisationId'] = ApiClient.convertToType(data['OrganisationId'], 'Number');
      }
      if (data.hasOwnProperty('IsCurrent')) {
        obj['IsCurrent'] = ApiClient.convertToType(data['IsCurrent'], 'Boolean');
      }
      if (data.hasOwnProperty('HourlyRate')) {
        obj['HourlyRate'] = ApiClient.convertToType(data['HourlyRate'], 'Number');
      }
      if (data.hasOwnProperty('HourlyOvertimeRate')) {
        obj['HourlyOvertimeRate'] = ApiClient.convertToType(data['HourlyOvertimeRate'], 'Number');
      }
      if (data.hasOwnProperty('StartDateTime')) {
        obj['StartDateTime'] = ApiClient.convertToType(data['StartDateTime'], 'Date');
      }
      if (data.hasOwnProperty('EndDateTime')) {
        obj['EndDateTime'] = ApiClient.convertToType(data['EndDateTime'], 'Date');
      }
    }
    return obj;
  }

  /**
   * @member {Number} RateId
   */
  exports.prototype['RateId'] = undefined;
  /**
   * @member {Number} UserId
   */
  exports.prototype['UserId'] = undefined;
  /**
   * @member {Number} OrganisationId
   */
  exports.prototype['OrganisationId'] = undefined;
  /**
   * @member {Boolean} IsCurrent
   */
  exports.prototype['IsCurrent'] = undefined;
  /**
   * @member {Number} HourlyRate
   */
  exports.prototype['HourlyRate'] = undefined;
  /**
   * @member {Number} HourlyOvertimeRate
   */
  exports.prototype['HourlyOvertimeRate'] = undefined;
  /**
   * @member {Date} StartDateTime
   */
  exports.prototype['StartDateTime'] = undefined;
  /**
   * @member {Date} EndDateTime
   */
  exports.prototype['EndDateTime'] = undefined;



  return exports;
}));


