/**
 * ChronoSheets API
 * An API for integrating into ChronoSheets timesheets
 *
 * OpenAPI spec version: v1
 * Contact: lachlan@chronosheets.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ChronoSheetsClient/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ChronoSheetsApi) {
      root.ChronoSheetsApi = {};
    }
    root.ChronoSheetsApi.CsApiInsertOrganisationGroupRequest = factory(root.ChronoSheetsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CsApiInsertOrganisationGroupRequest model module.
   * @module ChronoSheetsClient/ChronoSheetsClientLibModel/CsApiInsertOrganisationGroupRequest
   * @version v1
   */

  /**
   * Constructs a new <code>CsApiInsertOrganisationGroupRequest</code>.
   * @alias module:ChronoSheetsClient/ChronoSheetsClientLibModel/CsApiInsertOrganisationGroupRequest
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>CsApiInsertOrganisationGroupRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:ChronoSheetsClient/ChronoSheetsClientLibModel/CsApiInsertOrganisationGroupRequest} obj Optional instance to populate.
   * @return {module:ChronoSheetsClient/ChronoSheetsClientLibModel/CsApiInsertOrganisationGroupRequest} The populated <code>CsApiInsertOrganisationGroupRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('OrganisationGroupName')) {
        obj['OrganisationGroupName'] = ApiClient.convertToType(data['OrganisationGroupName'], 'String');
      }
      if (data.hasOwnProperty('OrganisationGroupUserIds')) {
        obj['OrganisationGroupUserIds'] = ApiClient.convertToType(data['OrganisationGroupUserIds'], ['Number']);
      }
    }
    return obj;
  }

  /**
   * @member {String} OrganisationGroupName
   */
  exports.prototype['OrganisationGroupName'] = undefined;
  /**
   * @member {Array.<Number>} OrganisationGroupUserIds
   */
  exports.prototype['OrganisationGroupUserIds'] = undefined;



  return exports;
}));


