/**
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ChronoSheetsClient/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ChronoSheetsApi) {
      root.ChronoSheetsApi = {};
    }
    root.ChronoSheetsApi.CSTranscription = factory(root.ChronoSheetsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CSTranscription model module.
   * @module ChronoSheetsClient/ChronoSheetsClientLibModel/CSTranscription
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CSTranscription</code>.
   * @alias module:ChronoSheetsClient/ChronoSheetsClientLibModel/CSTranscription
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>CSTranscription</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:ChronoSheetsClient/ChronoSheetsClientLibModel/CSTranscription} obj Optional instance to populate.
   * @return {module:ChronoSheetsClient/ChronoSheetsClientLibModel/CSTranscription} The populated <code>CSTranscription</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Id')) {
        obj['Id'] = ApiClient.convertToType(data['Id'], 'Number');
      }
      if (data.hasOwnProperty('OrgId')) {
        obj['OrgId'] = ApiClient.convertToType(data['OrgId'], 'Number');
      }
      if (data.hasOwnProperty('FileAttachmentId')) {
        obj['FileAttachmentId'] = ApiClient.convertToType(data['FileAttachmentId'], 'Number');
      }
      if (data.hasOwnProperty('Created')) {
        obj['Created'] = ApiClient.convertToType(data['Created'], 'Date');
      }
      if (data.hasOwnProperty('Status')) {
        obj['Status'] = ApiClient.convertToType(data['Status'], 'String');
      }
      if (data.hasOwnProperty('MediaType')) {
        obj['MediaType'] = ApiClient.convertToType(data['MediaType'], 'String');
      }
      if (data.hasOwnProperty('Contents')) {
        obj['Contents'] = ApiClient.convertToType(data['Contents'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} Id
   */
  exports.prototype['Id'] = undefined;
  /**
   * @member {Number} OrgId
   */
  exports.prototype['OrgId'] = undefined;
  /**
   * @member {Number} FileAttachmentId
   */
  exports.prototype['FileAttachmentId'] = undefined;
  /**
   * @member {Date} Created
   */
  exports.prototype['Created'] = undefined;
  /**
   * @member {module:ChronoSheetsClient/ChronoSheetsClientLibModel/CSTranscription.StatusEnum} Status
   */
  exports.prototype['Status'] = undefined;
  /**
   * @member {module:ChronoSheetsClient/ChronoSheetsClientLibModel/CSTranscription.MediaTypeEnum} MediaType
   */
  exports.prototype['MediaType'] = undefined;
  /**
   * @member {String} Contents
   */
  exports.prototype['Contents'] = undefined;


  /**
   * Allowed values for the <code>Status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "Saved"
     * @const
     */
    "Saved": "Saved",
    /**
     * value: "Processing"
     * @const
     */
    "Processing": "Processing",
    /**
     * value: "Completed"
     * @const
     */
    "Completed": "Completed",
    /**
     * value: "FailedWithError"
     * @const
     */
    "FailedWithError": "FailedWithError"  };

  /**
   * Allowed values for the <code>MediaType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.MediaTypeEnum = {
    /**
     * value: "Other"
     * @const
     */
    "Other": "Other",
    /**
     * value: "Mp3"
     * @const
     */
    "Mp3": "Mp3",
    /**
     * value: "Mp4"
     * @const
     */
    "Mp4": "Mp4",
    /**
     * value: "Wav"
     * @const
     */
    "Wav": "Wav",
    /**
     * value: "Flac"
     * @const
     */
    "Flac": "Flac"  };


  return exports;
}));


