/*
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ChronoSheetsClient/ApiClient', 'ChronoSheetsClient/ChronoSheetsClientLibModel/CSBasicCoordinate'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CSBasicCoordinate'));
  } else {
    // Browser globals (root is window)
    if (!root.ChronoSheetsApi) {
      root.ChronoSheetsApi = {};
    }
    root.ChronoSheetsApi.CSUpdateGeoFenceRequest = factory(root.ChronoSheetsApi.ApiClient, root.ChronoSheetsApi.CSBasicCoordinate);
  }
}(this, function(ApiClient, CSBasicCoordinate) {
  'use strict';

  /**
   * The CSUpdateGeoFenceRequest model module.
   * @module ChronoSheetsClient/ChronoSheetsClientLibModel/CSUpdateGeoFenceRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CSUpdateGeoFenceRequest</code>.
   * A request object for updating a new geofence
   * @alias module:ChronoSheetsClient/ChronoSheetsClientLibModel/CSUpdateGeoFenceRequest
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>CSUpdateGeoFenceRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:ChronoSheetsClient/ChronoSheetsClientLibModel/CSUpdateGeoFenceRequest} obj Optional instance to populate.
   * @return {module:ChronoSheetsClient/ChronoSheetsClientLibModel/CSUpdateGeoFenceRequest} The populated <code>CSUpdateGeoFenceRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('GeofenceId'))
        obj.geofenceId = ApiClient.convertToType(data['GeofenceId'], 'Number');
      if (data.hasOwnProperty('Name'))
        obj.name = ApiClient.convertToType(data['Name'], 'String');
      if (data.hasOwnProperty('FenceCoordinates'))
        obj.fenceCoordinates = ApiClient.convertToType(data['FenceCoordinates'], [CSBasicCoordinate]);
      if (data.hasOwnProperty('TriggerJobCodeId'))
        obj.triggerJobCodeId = ApiClient.convertToType(data['TriggerJobCodeId'], 'Number');
      if (data.hasOwnProperty('TriggerTaskId'))
        obj.triggerTaskId = ApiClient.convertToType(data['TriggerTaskId'], 'Number');
      if (data.hasOwnProperty('SendAlertToOrgGroupId'))
        obj.sendAlertToOrgGroupId = ApiClient.convertToType(data['SendAlertToOrgGroupId'], 'Number');
      if (data.hasOwnProperty('AlertSettings'))
        obj.alertSettings = ApiClient.convertToType(data['AlertSettings'], 'String');
      if (data.hasOwnProperty('TriggerSettings'))
        obj.triggerSettings = ApiClient.convertToType(data['TriggerSettings'], 'String');
      if (data.hasOwnProperty('StartTimeHour'))
        obj.startTimeHour = ApiClient.convertToType(data['StartTimeHour'], 'Number');
      if (data.hasOwnProperty('StartTimeMinute'))
        obj.startTimeMinute = ApiClient.convertToType(data['StartTimeMinute'], 'Number');
      if (data.hasOwnProperty('EndTimeHour'))
        obj.endTimeHour = ApiClient.convertToType(data['EndTimeHour'], 'Number');
      if (data.hasOwnProperty('EndTimeMinute'))
        obj.endTimeMinute = ApiClient.convertToType(data['EndTimeMinute'], 'Number');
    }
    return obj;
  }

  /**
   * The ID of the geofence you want to update
   * @member {Number} geofenceId
   */
  exports.prototype.geofenceId = undefined;

  /**
   * The name of the geo fence
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * A list of coordinates specifying the geofence region
   * @member {Array.<module:ChronoSheetsClient/ChronoSheetsClientLibModel/CSBasicCoordinate>} fenceCoordinates
   */
  exports.prototype.fenceCoordinates = undefined;

  /**
   * The job code to be used when the person enters/leaves the geofence
   * @member {Number} triggerJobCodeId
   */
  exports.prototype.triggerJobCodeId = undefined;

  /**
   * The task to be used when the person enters/leaves the geofence
   * @member {Number} triggerTaskId
   */
  exports.prototype.triggerTaskId = undefined;

  /**
   * Send an alert to a user, specified by their user ID
   * @member {Number} sendAlertToOrgGroupId
   */
  exports.prototype.sendAlertToOrgGroupId = undefined;

  /**
   * Define when you want the alerts to be setn
   * @member {module:ChronoSheetsClient/ChronoSheetsClientLibModel/CSUpdateGeoFenceRequest.AlertSettingsEnum} alertSettings
   */
  exports.prototype.alertSettings = undefined;

  /**
   * Define how to you want to trigger the timesheet automation
   * @member {module:ChronoSheetsClient/ChronoSheetsClientLibModel/CSUpdateGeoFenceRequest.TriggerSettingsEnum} triggerSettings
   */
  exports.prototype.triggerSettings = undefined;

  /**
   * The start hour in which this geofence should apply.  After this time, the geofence will be active.
   * @member {Number} startTimeHour
   */
  exports.prototype.startTimeHour = undefined;

  /**
   * The start minute in which this geofence should apply.  After this time, the geofence will be active.
   * @member {Number} startTimeMinute
   */
  exports.prototype.startTimeMinute = undefined;

  /**
   * The end hour in which this geofence will stop applying.  After this time, the geofence will be inactive.
   * @member {Number} endTimeHour
   */
  exports.prototype.endTimeHour = undefined;

  /**
   * The end minute in which this geofence will stop applying.  After this time, the geofence will be inactive.
   * @member {Number} endTimeMinute
   */
  exports.prototype.endTimeMinute = undefined;


  /**
   * Allowed values for the <code>alertSettings</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AlertSettingsEnum = {
    /**
     * value: "None"
     * @const
     */
    none: "None",

    /**
     * value: "SendWhenEntering"
     * @const
     */
    sendWhenEntering: "SendWhenEntering",

    /**
     * value: "SendWhenExiting"
     * @const
     */
    sendWhenExiting: "SendWhenExiting",

    /**
     * value: "SendWhenEnteringOrExiting"
     * @const
     */
    sendWhenEnteringOrExiting: "SendWhenEnteringOrExiting"
  };


  /**
   * Allowed values for the <code>triggerSettings</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TriggerSettingsEnum = {
    /**
     * value: "None"
     * @const
     */
    none: "None",

    /**
     * value: "StartTimesheetWhenEntering"
     * @const
     */
    startTimesheetWhenEntering: "StartTimesheetWhenEntering",

    /**
     * value: "StopTimesheetWhenEntering"
     * @const
     */
    stopTimesheetWhenEntering: "StopTimesheetWhenEntering",

    /**
     * value: "StartOnEnterStopOnLeave"
     * @const
     */
    startOnEnterStopOnLeave: "StartOnEnterStopOnLeave"
  };

  return exports;

}));
