/**
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InsertOrganisationGroupRequest model module.
 * @module ChronoSheetsClient/ChronoSheetsClientLibModel/InsertOrganisationGroupRequest
 * @version 1.0.0
 */
class InsertOrganisationGroupRequest {
    /**
     * Constructs a new <code>InsertOrganisationGroupRequest</code>.
     * Fields for inserting a new Organisation Group
     * @alias module:ChronoSheetsClient/ChronoSheetsClientLibModel/InsertOrganisationGroupRequest
     */
    constructor() { 
        
        InsertOrganisationGroupRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InsertOrganisationGroupRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:ChronoSheetsClient/ChronoSheetsClientLibModel/InsertOrganisationGroupRequest} obj Optional instance to populate.
     * @return {module:ChronoSheetsClient/ChronoSheetsClientLibModel/InsertOrganisationGroupRequest} The populated <code>InsertOrganisationGroupRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InsertOrganisationGroupRequest();

            if (data.hasOwnProperty('OrganisationGroupName')) {
                obj['OrganisationGroupName'] = ApiClient.convertToType(data['OrganisationGroupName'], 'String');
            }
            if (data.hasOwnProperty('OrganisationGroupUserIds')) {
                obj['OrganisationGroupUserIds'] = ApiClient.convertToType(data['OrganisationGroupUserIds'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * The name of the new Organisation Group.  This is used when you're looking up Organisation Groups elsewhere through ChronoSheets
 * @member {String} OrganisationGroupName
 */
InsertOrganisationGroupRequest.prototype['OrganisationGroupName'] = undefined;

/**
 * The Ids of the Users that are going to be in this Organisation Group
 * @member {Array.<Number>} OrganisationGroupUserIds
 */
InsertOrganisationGroupRequest.prototype['OrganisationGroupUserIds'] = undefined;






export default InsertOrganisationGroupRequest;

