/**
 * ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TimeSlot model module.
 * @module ChronoSheetsClient/ChronoSheetsClientLibModel/TimeSlot
 * @version 1.0.0
 */
class TimeSlot {
    /**
     * Constructs a new <code>TimeSlot</code>.
     * @alias module:ChronoSheetsClient/ChronoSheetsClientLibModel/TimeSlot
     */
    constructor() { 
        
        TimeSlot.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TimeSlot</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:ChronoSheetsClient/ChronoSheetsClientLibModel/TimeSlot} obj Optional instance to populate.
     * @return {module:ChronoSheetsClient/ChronoSheetsClientLibModel/TimeSlot} The populated <code>TimeSlot</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TimeSlot();

            if (data.hasOwnProperty('DayType')) {
                obj['DayType'] = ApiClient.convertToType(data['DayType'], 'String');
            }
            if (data.hasOwnProperty('UsualHourId')) {
                obj['UsualHourId'] = ApiClient.convertToType(data['UsualHourId'], 'Number');
            }
            if (data.hasOwnProperty('StartHour')) {
                obj['StartHour'] = ApiClient.convertToType(data['StartHour'], 'Number');
            }
            if (data.hasOwnProperty('StartMinute')) {
                obj['StartMinute'] = ApiClient.convertToType(data['StartMinute'], 'Number');
            }
            if (data.hasOwnProperty('EndHour')) {
                obj['EndHour'] = ApiClient.convertToType(data['EndHour'], 'Number');
            }
            if (data.hasOwnProperty('EndMinute')) {
                obj['EndMinute'] = ApiClient.convertToType(data['EndMinute'], 'Number');
            }
            if (data.hasOwnProperty('IsValid')) {
                obj['IsValid'] = ApiClient.convertToType(data['IsValid'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:ChronoSheetsClient/ChronoSheetsClientLibModel/TimeSlot.DayTypeEnum} DayType
 */
TimeSlot.prototype['DayType'] = undefined;

/**
 * @member {Number} UsualHourId
 */
TimeSlot.prototype['UsualHourId'] = undefined;

/**
 * @member {Number} StartHour
 */
TimeSlot.prototype['StartHour'] = undefined;

/**
 * @member {Number} StartMinute
 */
TimeSlot.prototype['StartMinute'] = undefined;

/**
 * @member {Number} EndHour
 */
TimeSlot.prototype['EndHour'] = undefined;

/**
 * @member {Number} EndMinute
 */
TimeSlot.prototype['EndMinute'] = undefined;

/**
 * @member {Boolean} IsValid
 */
TimeSlot.prototype['IsValid'] = undefined;





/**
 * Allowed values for the <code>DayType</code> property.
 * @enum {String}
 * @readonly
 */
TimeSlot['DayTypeEnum'] = {

    /**
     * value: "Monday"
     * @const
     */
    "Monday": "Monday",

    /**
     * value: "Tuesday"
     * @const
     */
    "Tuesday": "Tuesday",

    /**
     * value: "Wednesday"
     * @const
     */
    "Wednesday": "Wednesday",

    /**
     * value: "Thursday"
     * @const
     */
    "Thursday": "Thursday",

    /**
     * value: "Friday"
     * @const
     */
    "Friday": "Friday",

    /**
     * value: "Saturday"
     * @const
     */
    "Saturday": "Saturday",

    /**
     * value: "Sunday"
     * @const
     */
    "Sunday": "Sunday"
};



export default TimeSlot;

