/**
 * The ChronoSheets API
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  </p>  <p>      First Steps:       <ol>          <li>Make sure you've <a href='/HomeV2/App/sign-up'>signed up to ChronoSheets</a> to get yourself a user account</li>          <li>Confirm your account by following the link sent to your email address.  This will activate your account</li>          <li>Use your username and password to obtain an Auth Token by using the DoLogin method inside the UserProfile section below.  Use the Auth Token as an argument to the other methods</li>          <li>Try different methods in the API Playground to learn about the API</li>          <li>If you're stuck, try the full getting started guide on the <a href='/Home/ApiDocs'>API Toolkit</a> page.</li>      </ol>  </p>  <p>      Further Steps:       <ul>          <li>Create a mobile app (iOS, Android or Windows) using one of the ChronoSheets Mobile SDKs</li>          <li>Create a custom integration with your app using one of the ChronoSheets API Client Libraries.</li>      </ul>      Read more about the API Toolkit on the <a href='/Home/ApiDocs'>API Toolkit</a> page.  </p></div>
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TheChronoSheetsApi);
  }
}(this, function(expect, TheChronoSheetsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TheChronoSheetsApi.CSTimesheet();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CSTimesheet', function() {
    it('should create an instance of CSTimesheet', function() {
      // uncomment below and update the code to test CSTimesheet
      //var instane = new TheChronoSheetsApi.CSTimesheet();
      //expect(instance).to.be.a(TheChronoSheetsApi.CSTimesheet);
    });

    it('should have the property timesheetId (base name: "TimesheetId")', function() {
      // uncomment below and update the code to test the property timesheetId
      //var instane = new TheChronoSheetsApi.CSTimesheet();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "UserId")', function() {
      // uncomment below and update the code to test the property userId
      //var instane = new TheChronoSheetsApi.CSTimesheet();
      //expect(instance).to.be();
    });

    it('should have the property jobId (base name: "JobId")', function() {
      // uncomment below and update the code to test the property jobId
      //var instane = new TheChronoSheetsApi.CSTimesheet();
      //expect(instance).to.be();
    });

    it('should have the property taskId (base name: "TaskId")', function() {
      // uncomment below and update the code to test the property taskId
      //var instane = new TheChronoSheetsApi.CSTimesheet();
      //expect(instance).to.be();
    });

    it('should have the property startDateTime (base name: "StartDateTime")', function() {
      // uncomment below and update the code to test the property startDateTime
      //var instane = new TheChronoSheetsApi.CSTimesheet();
      //expect(instance).to.be();
    });

    it('should have the property endDateTime (base name: "EndDateTime")', function() {
      // uncomment below and update the code to test the property endDateTime
      //var instane = new TheChronoSheetsApi.CSTimesheet();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "Description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new TheChronoSheetsApi.CSTimesheet();
      //expect(instance).to.be();
    });

    it('should have the property tripId (base name: "TripId")', function() {
      // uncomment below and update the code to test the property tripId
      //var instane = new TheChronoSheetsApi.CSTimesheet();
      //expect(instance).to.be();
    });

    it('should have the property fileAttachmentCount (base name: "FileAttachmentCount")', function() {
      // uncomment below and update the code to test the property fileAttachmentCount
      //var instane = new TheChronoSheetsApi.CSTimesheet();
      //expect(instance).to.be();
    });

    it('should have the property payAmount (base name: "PayAmount")', function() {
      // uncomment below and update the code to test the property payAmount
      //var instane = new TheChronoSheetsApi.CSTimesheet();
      //expect(instance).to.be();
    });

    it('should have the property overtimePayAmount (base name: "OvertimePayAmount")', function() {
      // uncomment below and update the code to test the property overtimePayAmount
      //var instane = new TheChronoSheetsApi.CSTimesheet();
      //expect(instance).to.be();
    });

    it('should have the property includesOvertime (base name: "IncludesOvertime")', function() {
      // uncomment below and update the code to test the property includesOvertime
      //var instane = new TheChronoSheetsApi.CSTimesheet();
      //expect(instance).to.be();
    });

  });

}));
